name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      # Get updated translations
      - name: Download Lokalise CLI
        run: |
          curl -sSL \
            "https://s3-eu-west-1.amazonaws.com/lokalise-assets/cli/lokalise-0.721-linux-amd64.tgz" \
            -o ./lokalise.tgz
          tar -xvzf ./lokalise.tgz
      - name: Downloading translations
        run: |
          ./lokalise \
              --token "${{ secrets.lokalise_token }}" \
              export "190570815d9461966ae081.06523141" \
              --type json \
              --unzip_to  /tmp/lokalise \
              --filter last_reviewed_only \
              --export_empty skip \
              --export_sort a_z

      - name: Move new  translations
        run: |
          mkdir -p /home/runner/work/integration/integration/custom_components/hacs/.translations/
          cp /tmp/lokalise/locale/* /home/runner/work/integration/integration/custom_components/hacs/.translations/

      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ github.ref }}"' /home/runner/work/integration/integration/custom_components/hacs/const.py
          sed -i 's|refs/heads/||' /home/runner/work/integration/integration/custom_components/hacs/const.py
          sed -i 's|refs/tags/||' /home/runner/work/integration/integration/custom_components/hacs/const.py

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP HACS Dir
        run: |
          cd /home/runner/work/integration/integration/custom_components/hacs
          zip hacs.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/integration/integration/custom_components/hacs/hacs.zip
          asset_name: hacs.zip
          tag: ${{ github.ref }}
          overwrite: true


  releasenotes:
    name: Prepare releasenotes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Enable version 3.7 of Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel
          python3 -m pip install -r /home/runner/work/integration/integration/requirements.txt

      - name: Update release notes
        run: python3 /home/runner/work/integration/integration/manage/generate_releasenotes.py --token ${{ secrets.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }}